spring:
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: create
  output:
    ansi:
      enabled: always
  profiles:
    default: dev

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem

sentry:
  dsn: https://b5602824b1082ee05b0f4c7c45fae7cf@o4506474496983040.ingest.sentry.io/4506474877550592
  traces-sample-rate: 1.0
