spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  output:
    ansi:
      enabled: always

rsa:
  private-key: classpath:certs/private.pem
  public-key: classpath:certs/public.pem
